# Generated by Django 3.1.7 on 2021-04-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'RecipeCategories'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
