# Generated by Django 3.1.7 on 2021-04-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210416_2311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at']},
        ),
    ]
